### ISSUE TITLE
disappearing puzzles

### ISSUE THREAD

**Issue by tckmn** [robx/puzzledb#21]
I have no idea if this is some strange issue on my end, but recently the following has started happening: I click on a puzzle from the db, solve the puzzle, and when I close the tab and refocus the db tab, some of the puzzles in the list disappear (so there are now fewer than 10). I have no idea what causes this or how to reproduce it, but it happens on Firefox 75.0 on Nixos.

**Comment by edderiofer** [comment]
This may be due to people deleting puzzles they've tweeted shortly after publishing said puzzles, but I have no evidence to support this hypothesis.

**Comment by robx** [comment]
Deleted puzzles are the most likely explanation, yes (and that would be as designed).

**Comment by robx** [comment]
Closing this since deletion seems a likely explanation, do reopen if you see this happening in a way the doesn't align with tweet deletion.
