### ISSUE TITLE
About that change of the links in database

### ISSUE THREAD

**Issue by psml-imeji** [robx/puzzledb#25]
I think there should still has the links to the puzz.link page like before, since after the change you need to open the source page before you can go to the puzz.link page, which means start to solving those puzzles would become much slower, and may not even able to play those puzzles if those sources got blocked.

**Comment by psml-imeji** [comment]
@robx After this change I can not longer to play the most of those puzzles without a proxy.

**Comment by psml-imeji** [comment]
Made a JS script that can change the links on those puzzles based on the link of the sample pictures.
Open those codes below like a web link in your browser to change those links.
If this way did not works on your browser, remove the "javascript:" in the very first of this code, and then press F12, paste them in the console to use them.

```
javascript:void(function() {
  for(var x=1; x<=10; x++) {
    var link = document.querySelector('body > div > ul > li:nth-child(' + x + ') > div.thumb > a > img').src;
    link = link.replace('https://puzz.link/pv?thumb&', 'https://puzz.link/p?');
    document.querySelector('body > div > ul > li:nth-child(' + x + ') > div:nth-child(3) > a').href = link;
    document.querySelector('body > div > ul > li:nth-child(' + x + ') > div:nth-child(3) > a').innerHTML = link;
  }
})()
```

**Comment by shadowstejo** [comment]
yes. I agree. sometimes I get redirects to deleted tweets or some 100 comment thread where I can't find the link to the puzzle.
make it so that when you click the picture you get the puzzle and when u click the link, u get the link.
ありがとう。

**Comment by robx** [comment]
There's some discussion around this over on the zulip, e.g. https://puzzlink.zulipchat.com/#narrow/stream/225985-puzzle-db/topic/direct.20puzzle.20links.20removed.20%28for.20the.20moment%29/near/214912017

Current status is that this won't change, for better or worse.
