### ISSUE TITLE
Solved puzzles and difficulty are no longer properly recorded

### ISSUE THREAD

**Issue by moppman** [robx/puzzledb#29]
Hi!
For some time (not sure how long exactly, couple of weeks?) puzzles don't seem to be registered as "solved" anymore, thus the difficulty rating (on hover) is no longer shown for most of new puzzles and it just says `solves: 0`. There are some new puzzles where it still seems to work, but I haven't been able to recognize a pattern.

**Comment by jeffreybardon** [comment]
The pattern is theorized to be that solves logged after the db picks up the puzzle are not saved, while solves from before that point (from sharing it privately etc.) are.

**Comment by moppman** [comment]
> The pattern is theorized to be that solves logged after the db picks up the puzzle are not saved, while solves from before that point (from sharing it privately etc.) are.

Ah, thanks! Has this always been the case? Looking at past puzzles, it looks to me like the behaviour has changed around the beginning of October.
Or maybe people have just been solving fewer puzzles 😅

**Comment by moppman** [comment]
Ok, looks like everything's working again after a day or two of `503` status code messages. Guess I'll close this now.
