### ISSUE TITLE
Bad URLs from blog feed

### ISSUE THREAD

**Issue by montelucci** [robx/puzzledb#3]
Links from https://aoiatuage.com/archives/769 appear in the db with an extra `</a` at the end

**Comment by montelucci** [comment]
As a side effect these puzzles are not properly marked solved in the db, likely because solves are sent with ending `%3C/a`, so the solve URL and the db URL don't match

**Comment by robx** [comment]
That was a funny bug, introduced when changing things to accept the `=` for a recent factors puzzle.

It turns out that this was not how to do that:

```
-                     '(https?://(?:www\.)?(?:pzv.jp|puzz.link)/p(?:\.html)?\?[*a-zA-Z0-9_/.%$+-]*)', 'g');
+                     '(https?://(?:www\.)?(?:pzv.jp|puzz.link)/p(?:\.html)?\?[*a-zA-Z0-9_/.%$+-=]*)', 'g');
```
