### ISSUE TITLE
Allow variant puzzles to have some kind of additional modifier marker

### ISSUE THREAD

**Issue by jim-hays-root** [robx/puzzledb#30]
It would be nice to be able to add some kind of modifier marker to cells in puzzles.  This modifier marker could be similar to the symbol used for starting a trial, for example, but maybe it would be a different shape or color. This modifier would be able to be added as part of creating the grid, but would not affect any of the solving logic.  Here are two examples of how it could be used:
1) The link below is to a Nurikabe variant, but with the additional constraint that each region with a number contains a scarecrow. If when creating and sharing a puzzle it were possible to mark the scarecrow cells in some way, that would allow for capturing much more of the puzzle.
http://puzzledpint.com/files/9316/3931/7781/Main_Set_-_Gilligans_Island_2.pdf
2) A Nonogram that is laid out in a grid but which has a non-rectangular border (for example, approximating a right triangle, or a circle).  Users could embed the irregular shape in a larger rectanglar grid, then use the modifier to highlight all of the off-limit squares.  This same accommodation would then allow for a variety of non-rectangular grids.

There are likely many other ways this one feature could be used to create custom puzzle variants.

**Comment by moppman** [comment]
For those who want to playtest the variant: [here's the Penpa+ link](https://tinyurl.com/yajq5tp4) for the Nurikabe variant from the pdf linked in the OP. 
(I used minesweeper bombs instead of scarecrows :)  )

**Comment by robx** [comment]
This would be a feature for github.com/robx/pzprjs (the player applet), not the database.

However, I don't think this kind of support for variants is a good fit, penpa seems to be a better choice for that kind of puzzle.
