### ISSUE TITLE
My tweet puzzle is not apprearing in the database.

### ISSUE THREAD

**Issue by psml-imeji** [robx/puzzledb#31]
Here is one of the unlisted puzzle:
https://twitter.com/primarina_P/status/1554379126483853312?s=20

I have more puzzles like that was not listed. Please tell me if there is any way to get it listed.

**Comment by robx** [comment]
It's there now, by running an explicit import on your twitter account. Unfortunately it's a known issue that the twitter feed misses some posts, and so far there's no automatic way to fetch the missed puzzles.
