### ISSUE TITLE
HTTP 503 errors instead of puzzles

### ISSUE THREAD

**Issue by AlbeyAmakiir** [robx/puzzledb#36]
For the past few days, when I go to https://puzz.link/db/ I don't see any puzzles listed. Instead, after the login section and filter controls, I see a red box that reads:

> - logging in: 503
> - loading puzzles: 503
> - loading puzzle types: 503 

And when I switch away from and back to the tab, it adds:

> - refreshing puzzles: 503 

503 is the code for "the server is unavailable", normally used when a server is in maintenance or overloaded.

**Comment by Oripy** [comment]
I'm getting worried that the person responsible for the server maintenance is no longer working on this. Do we know who was in charge of this server?

**Comment by Oripy** [comment]
It seems to be resolved!

**Comment by AlbeyAmakiir** [comment]
Huzzah!
I... think that means I can close my own issue now?
