### ISSUE TITLE
Place Given Digits in Skyscrapers/Doppelblock/Kropki/etc.

### ISSUE THREAD

**Issue by jeffreybardon** [robx/puzzledb#5]
Some puzzle types don't support placing digits into the grid, only clues. This shouldn't be the case, as puzzles exist in all three of those types with given numbers.

Rooms of Factors is another type that suffers from this problem, in addition to not allowing unclued rooms. There may be others that I'm forgetting right now.

**Comment by robx** [comment]
This is not an issue with the database, but with https://github.com/robx/pzprjs. (Also, I disagree that the puzzle applet needs to support all puzzles that exist.)
