### ISSUE TITLE
Add user stats.

### ISSUE THREAD

**Issue by edderiofer** [robx/puzzledb#8]
So that people can track how many of each type of puzzle they've solved, how many they've skipped, and so on. Probably just privately-accessible for now, but a public opt-in leaderboard would also be nice.

**Comment by robx** [comment]
So let's see, there's some overlap with #9 

How about:

- we calculate total numbers of puzzles grouped by puzzle type and source offline (and perhaps some time component? per month maybe?). this is #9 
- per user we calculate number solved / skipped for each of these buckets (probably online, should not be too heavy... unless you've solved too many and those are the likely people having this on reload 😬 )

How might this be displayed?

**Comment by edderiofer** [comment]
Well, here's how PuzzlePicnic displays statistics. I think it's probably fine to forgo the graphs and bar charts, and just have a (collapsible) list of genres and the number of solved/skipped puzzles per genre; likewise for source/author and difficulty.

![image](https://user-images.githubusercontent.com/16442480/77104370-d6452500-6a13-11ea-9836-0b44a41e9e02.png)

**Comment by robx** [comment]
Hmm I was looking more for a simple table layout here.

**Comment by robx** [comment]
There are some global stats now at https://puzz.link/db/stats.html. The idea for this one would be that each of these tables gets extra columns "solved", "skipped" for the current user.

**Comment by robx** [comment]
If you're logged in, you now see number of solved and skipped puzzles on that page, too.
